#1.控制台日志颜色输出配置
spring:
  output:
    ansi:
      enabled: always #进行颜色输出,容易查找。你也可以安装插件。
  #2.项目logo配置
  banner:
    charset: UTF-8
    location: classpath:banner.txt
  #3.配置devtools。一般不用配置，默认就好。这里只是学习案例。
  devtools:
    restart:
      enabled: true
      exclude: META-INF/maven/**,META-INF/resources/**,resources/**,static/**,public/**,templates/**,**/*Test.class,**/*Tests.class,git.properties,META-INF/build-info.properties#默认修改不重启项目的路径
#########################################
#
#   SpringBoot整合FreeMarker的相关配置
#
#########################################
  freemarker: 
    template-loader-path:
    - classpath:/templates/freemarker
    enabled: false
    cache: false
    charset: UTF-8
    check-template-location: true
    content-type: text/html; charset=utf-8
    expose-request-attributes: true
    expose-session-attributes: true
    request-context-attribute: request
    suffix: .ftl
#########################################
#
#   SpringBoot整合Thymeleaf的相关配置
#
#########################################
  thymeleaf:
    enabled: true
    cache: false
    check-template: true
    encoding: UTF-8
    mode: HTML
    servlet:
      content-type: text/html; charset=utf-8
    prefix: classpath:/templates/thymeleaf/
    suffix: .html
  #配置静态文件路径
  mvc:
    static-path-pattern: /static/**   #一定要加**，不然坑死你
###########################################################
#
#   SpringBoot通过application.yml读取配置文件给thymeleaf使用
#
###########################################################  
  messages:
    fallback-to-system-locale: true  
    basename: i18n/messages
    cache-duration:
      seconds: 60
    encoding: UTF-8
  #激活使用的配置文件联合使用dev为主
  profiles:
    active:
    - dev
    
#配置该项目的访问路径和服务器tomcat的端口号，URI的编码；（服务器相关的配置）
server:
  servlet:
    context-path: /springbootstudy
  tomcat:
    uri-encoding: UTF-8
  port: 8888
    