#控制台日志颜色输出配置
spring:
  output:
    ansi:
      enabled: always #进行颜色输出,容易查找。你也可以安装插件。
  #项目logo配置
  banner:
    charset: UTF-8
    location: classpath:banner.txt
  #配置devtools。一般不用配置，默认就好。这里只是学习案例。
  devtools:
    restart:
      enabled: true
      exclude: META-INF/maven/**,META-INF/resources/**,resources/**,static/**,public/**,templates/**,**/*Test.class,**/*Tests.class,git.properties,META-INF/build-info.properties#默认修改不重启项目的路径
server:
  servlet:
    #配置项目访问前置路径
    context-path: /springbootstudy